version: "3.3"

services:
  qix-engine:
    image: qlikcore/engine:12.350.0
    ports:
      - 9076:9076
    command: -S AcceptEULA=${ACCEPT_EULA} -S EnableGrpcFileStreamConnector=1 -S GrpcConnectorPlugins="s3-grpc-file-connector,s3-grpc-file-connector:50051,fs" -S ScriptLogVerbosity=5
  s3-grpc-file-connector:
    build: ../
    ports:
      - 50051:50051
    environment:
      CORE_S3_FILE_CONNECTOR_BUCKET_NAME: ${CORE_S3_FILE_CONNECTOR_BUCKET_NAME}
      CORE_S3_FILE_CONNECTOR_BUCKET_ACCESS_KEY_ID: ${CORE_S3_FILE_CONNECTOR_BUCKET_ACCESS_KEY_ID}
      CORE_S3_FILE_CONNECTOR_BUCKET_SECRET_ACCESS_KEY: ${CORE_S3_FILE_CONNECTOR_BUCKET_SECRET_ACCESS_KEY}
